export const emblemTierMap = new Map([
  [1, 'Emblem_Iron.png'],
  [2, 'Emblem_Iron.png'],
  [3, 'Emblem_Iron.png'],
  [4, 'Emblem_Iron.png'],
  [5, 'Emblem_Bronze.png'],
  [6, 'Emblem_Bronze.png'],
  [7, 'Emblem_Bronze.png'],
  [8, 'Emblem_Bronze.png'],
  [9, 'Emblem_Silver.png'],
  [10, 'Emblem_Silver.png'],
  [11, 'Emblem_Silver.png'],
  [12, 'Emblem_Silver.png'],
  [13, 'Emblem_Gold.png'],
  [14, 'Emblem_Gold.png'],
  [15, 'Emblem_Gold.png'],
  [16, 'Emblem_Gold.png'],
  [17, 'Emblem_Platinum.png'],
  [18, 'Emblem_Platinum.png'],
  [19, 'Emblem_Platinum.png'],
  [20, 'Emblem_Platinum.png'],
  [21, 'Emblem_Diamond.png'],
  [22, 'Emblem_Diamond.png'],
  [23, 'Emblem_Diamond.png'],
  [24, 'Emblem_Diamond.png'],
  [25, 'Emblem_Master.png'],
]);
